# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: msuarez- <msuarez-@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/24 16:34:52 by msuarez-          #+#    #+#              #
#    Updated: 2019/07/24 16:34:53 by msuarez-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_cat
SRCS=srcs/*.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean re
